const MRT = "/data/adb/modules/module-reflash-trigger/bin/mrt";
const $ = id => document.getElementById(id);
const state = { modules: [], filter: "all", selected: new Set(), lastDryRunWouldTrigger: 0, lastAutoWouldTrigger: 0, lastMode: "online", polling: null, job: {}, autoLoadedKey: "" };
const statusEl=$("status"), bridgeStatusEl=$("bridgeStatus"), rawEl=$("raw"), statsEl=$("stats"), filtersEl=$("filters"), modulesEl=$("modules"), allowlistEl=$("allowlist"), factsEl=$("jobFacts"), progressEl=$("progressBar"), nextStepEl=$("nextStep");
function shellQuote(s){ return "'" + String(s).replace(/'/g,"'\\''") + "'"; }
function bridgeCandidates(){ const out=[]; if(window.ksu&&typeof window.ksu.exec==="function") out.push(["ksu.exec",cmd=>window.ksu.exec(cmd)]); if(window.kernelsu&&typeof window.kernelsu.exec==="function") out.push(["kernelsu.exec",cmd=>window.kernelsu.exec(cmd)]); if(window.apatch&&typeof window.apatch.exec==="function") out.push(["apatch.exec",cmd=>window.apatch.exec(cmd)]); if(window.magisk&&typeof window.magisk.exec==="function") out.push(["magisk.exec",cmd=>window.magisk.exec(cmd)]); if(window.webui&&typeof window.webui.exec==="function") out.push(["webui.exec",cmd=>window.webui.exec(cmd)]); return out; }
function execShell(cmd, quiet=false){ if(!quiet) rawEl.textContent="$ "+cmd+"\n\n"; const candidates=bridgeCandidates(); if(!candidates.length){ const msg="ERROR: no shell bridge object detected"; if(!quiet) rawEl.textContent+=msg; throw new Error(msg); } let last=""; for(const [name,fn] of candidates){ try{ const res=fn(cmd); bridgeStatusEl.textContent="Shell bridge: "+name; const s=String(res??"").trim(); if(!quiet) rawEl.textContent+=s; return s; }catch(e){ last=`${name}: ${e&&e.message?e.message:e}`; } } if(!quiet) rawEl.textContent+="ERROR: all shell bridge calls failed\n"+last; throw new Error(last); }
function parseSemi(text){ const o={}; String(text||"").trim().split(";").forEach(part=>{ const i=part.indexOf("="); if(i>=0) o[part.slice(0,i)]=part.slice(i+1); }); return o; }
function setStatus(msg){ statusEl.textContent=msg; }
function setNext(msg){ nextStepEl.innerHTML=msg; }
function nowSec(){ return Math.floor(Date.now()/1000); }
function jobAge(j){ const u=Number(j.updated||0); return u>0 ? Math.max(0, nowSec()-u) : null; }
function bytesForMode(j, mode){ return Number(mode==="local" ? (j.local_bytes||0) : (j.online_bytes||0)); }
function errBytesForMode(j, mode){ return Number(mode==="local" ? (j.local_err_bytes||0) : (j.online_err_bytes||0)); }
function visualState(j){ const age=jobAge(j); if((j.status||"")==="running" && age!==null && age>90) return "stale"; if((j.status||"")==="failed" || (j.status||"")==="error") return "failed"; if((j.status||"")==="ok" || (j.status||"")==="done") return "ok"; if((j.status||"")==="running") return "running"; return "idle"; }
function renderJob(){ const j=state.job||{}, mode=j.mode||state.lastMode||"online", v=visualState(j), age=jobAge(j); progressEl.className="progress-bar "+v; const cache=bytesForMode(j, mode), err=errBytesForMode(j, mode); const facts=[["state",v==="stale"?"stale":(j.status||"?")],["mode",mode||"?"],["pid",j.pid||""],["age",age===null?"?":age+"s"],["cache bytes",cache],["err bytes",err],["rc",j.rc||""],["loaded modules",state.modules.length]]; factsEl.innerHTML=facts.map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join(""); if(v==="ok"&&cache>0){ setNext("Scan complete. Results are ready; <strong>Load latest results</strong> will show module cards."); } else if(v==="running"){ setNext("Scan is running. This is an activity indicator, not a percent bar. You can wait here; status refreshes automatically."); } else if(v==="stale"){ setNext("Status looks stale. Use <strong>Refresh status</strong>, or <strong>Load latest results</strong> if cache bytes are present."); } else if(v==="failed"){ setNext("Scan failed. Check Raw output or error bytes before retrying."); } else if(cache>0){ setNext("Previous cache is available. Use <strong>Load latest results</strong> to show cards."); } }
function normalize(m){ if(m.self||m.status==="self") return "blocked"; if(m.disabled||m.remove_marker||m.status==="blocked") return "blocked"; if(m.status==="local_newer_than_remote") return "local_newer"; if(m.moduleNeedsReflashMarker||(m.status==="needs_reflash"&&m.reason==="module_reported_needs_reflash_marker")) return "needs"; if(m.status==="fresh") return "fresh"; if(m.needs_reflash||m.status==="needs_reflash"||m.reason==="remote_fingerprint_changed_since_last_fresh") return "drift"; return "unknown"; }
function counts(){ const c={needs:0,fresh:0,drift:0,unknown:0,local_newer:0,blocked:0,total:state.modules.length}; state.modules.forEach(m=>c[normalize(m)]++); return c; }
function renderStats(){ const c=counts(); const items=[["needs","Needs reflash",c.needs,"Manager marker"],["fresh","Fresh",c.fresh,"Baseline matches"],["drift","Drift",c.drift,"Diagnostic only"],["unknown","Unknown",c.unknown,"No baseline yet"],["local_newer","Local newer",c.local_newer,"No trigger"],["blocked","Blocked",c.blocked,"Unsafe target"],["all","Total",c.total,"updateJson-capable"]]; statsEl.innerHTML=items.map(([key,label,val,sub])=>`<button class="mrt-stat ${state.filter===key?"active":""}" data-filter="${key}"><span>${label}</span><strong>${val}</strong><small>${sub}</small></button>`).join(""); statsEl.querySelectorAll("button[data-filter]").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter; render();}); }
function renderFilters(){ const f=[["needs","Needs reflash"],["fresh","Fresh"],["drift","Drift"],["unknown","Unknown"],["local_newer","Local newer"],["blocked","Blocked"],["all","All"]]; filtersEl.innerHTML=f.map(([k,l])=>`<button class="chip ${state.filter===k?"active":""}" data-filter="${k}">${l}</button>`).join(""); filtersEl.querySelectorAll("button[data-filter]").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter; render();}); }
function field(label,value){ if(value===undefined||value===null||value==="") return ""; return `<div class="field"><span>${label}</span><code>${String(value)}</code></div>`; }
function card(m){ const n=normalize(m), checked=state.selected.has(m.id)?"checked":""; return `<article class="mrt-card ${n}"><div class="card-head"><div><label><input type="checkbox" data-select="${m.id}" ${checked}> <strong>${m.name||m.id}</strong></label><p><code>${m.id}</code></p></div><span class="badge ${n}">${n}</span></div><div class="fields">${field("version",m.version)}${field("versionCode",m.versionCode)}${field("remote",m.remoteVersion)}${field("remoteCode",m.remoteCode)}${field("reason",m.reason)}${field("marker",m.moduleNeedsReflashMarker)}${field("triggerable",m.triggerable)}</div><details class="advanced-actions"><summary>Module actions</summary><div class="card-actions"><button data-act="status" data-id="${m.id}">Status online</button><button class="danger" data-act="trigger" data-id="${m.id}" ${m.triggerable?"":"disabled"}>Trigger this module</button><button data-act="fresh" data-id="${m.id}">Mark fresh</button><button data-act="freshCached" data-id="${m.id}">Mark fresh cached</button><button data-act="baseline" data-id="${m.id}">Baseline</button><button data-act="clear" data-id="${m.id}">Clear baseline</button><button data-act="restore" data-id="${m.id}">Restore latest</button></div></details></article>`; }
function renderModules(){ let list=state.modules; if(state.filter!=="all") list=list.filter(m=>normalize(m)===state.filter); modulesEl.innerHTML=list.length?list.map(card).join(""):`<div class="empty">${state.modules.length?"No modules in this filter.":"No modules loaded yet. Use Scan online, then Load latest results."}</div>`; modulesEl.querySelectorAll("input[data-select]").forEach(cb=>cb.onchange=()=>{ if(cb.checked) state.selected.add(cb.dataset.select); else state.selected.delete(cb.dataset.select); }); modulesEl.querySelectorAll("button[data-act]").forEach(b=>b.onclick=()=>moduleAction(b.dataset.act,b.dataset.id)); }
function render(){ renderJob(); renderStats(); renderFilters(); renderModules(); $("bulkTrigger").disabled=state.lastDryRunWouldTrigger<=0; $("autoRun").disabled=state.lastAutoWouldTrigger<=0; }
function startScan(mode){ state.lastMode=mode; state.autoLoadedKey=""; setStatus(`Starting ${mode} scan…`); setNext("Starting background scan…"); state.modules=[]; render(); execShell(`${MRT} webui-scan-start ${mode}`); if(state.polling) clearInterval(state.polling); state.polling=setInterval(()=>pollStatus(true),3000); setTimeout(()=>pollStatus(true),900); }
function pollStatus(auto=false){ const out=execShell(`${MRT} webui-status-line`, false); const kv=parseSemi(out); state.job=kv; const v=visualState(kv), mode=kv.mode||state.lastMode; setStatus(`state=${v} mode=${mode||"?"} ${kv.message||""}`); render(); const cache=bytesForMode(kv, mode); if(auto && v==="ok" && cache>0){ if(state.polling){ clearInterval(state.polling); state.polling=null; } const key=`${mode}:${kv.updated}:${cache}`; if(state.autoLoadedKey!==key){ state.autoLoadedKey=key; setNext("Scan complete. Auto-loading latest results…"); setTimeout(()=>loadScan(mode||"online", true),250); } } if(v==="failed"){ if(state.polling){ clearInterval(state.polling); state.polling=null; } } }
function b64ToUtf8(b64){ if(!b64) return ""; const bin=atob(b64); const bytes=new Uint8Array(bin.length); for(let i=0;i<bin.length;i++) bytes[i]=bin.charCodeAt(i); return new TextDecoder("utf-8").decode(bytes); }
function readB64Chunks(mode){ let offset=0, chunks=[], limit=3072; for(let i=0;i<160;i++){ const b64=execShell(`${MRT} webui-read-b64 ${mode} ${offset} ${limit}`, true).trim(); if(!b64) break; const txt=b64ToUtf8(b64); chunks.push(txt); const size=new Blob([txt]).size; offset+=size; if(size<limit) break; } return chunks.join(""); }
function loadScan(mode, auto=false){ state.lastMode=mode; setStatus(`Loading ${mode} cache…`); const text=readB64Chunks(mode); rawEl.textContent=`Loaded ${text.length} chars from ${mode} cache\n\n`+text.slice(0,5000); try{ state.modules=JSON.parse(text); state.filter="all"; setStatus(`Loaded ${state.modules.length} modules from ${mode} cache.`); setNext("Results loaded. Review filters first; trigger actions are hidden inside each card's advanced actions."); }catch(e){ setStatus(`JSON parse failed: ${e.message}`); setNext("Cache could not be parsed. Run scan again or clear cache."); } render(); if(!auto) statsEl.scrollIntoView({block:"start", behavior:"smooth"}); }
function readOutput(name){ let offset=0, chunks=[], limit=3072; for(let i=0;i<40;i++){ const b64=execShell(`${MRT} webui-output-read-b64 ${name} ${offset} ${limit}`, true).trim(); if(!b64) break; const txt=b64ToUtf8(b64); chunks.push(txt); const size=new Blob([txt]).size; offset+=size; if(size<limit) break; } return chunks.join(""); }
function run(cmd){ try{ const out=execShell(cmd); setStatus("Command finished."); return out; }catch(e){ setStatus("Command failed: "+e.message); return ""; } }
function runLine(cmd){ try{ const out=execShell(cmd); setStatus("Command finished."); return parseSemi(out); }catch(e){ setStatus("Command failed: "+e.message); return {}; } }
function moduleAction(act,id){ const q=shellQuote(id); if(act==="trigger"&&!confirm(`Trigger ${id}? This lowers version/versionCode only. Your manager must perform the actual reflash.`)) return; const map={status:`${MRT} status-online ${q}`,trigger:`${MRT} trigger --yes ${q}`,fresh:`${MRT} mark-fresh ${q}`,freshCached:`${MRT} mark-fresh-cached ${q}`,baseline:`${MRT} baseline-show --online ${q}`,clear:`${MRT} clear-baseline ${q}`,restore:`${MRT} restore-latest ${q}`}; run(map[act]||`${MRT} status-online ${q}`); }
$("scanOnline").onclick=()=>startScan("online"); $("scanLocal").onclick=()=>startScan("local"); $("loadOnline").onclick=()=>loadScan("online"); $("loadLocal").onclick=()=>loadScan("local"); $("refreshJob").onclick=()=>pollStatus(false); $("clearCache").onclick=()=>{ state.modules=[]; const out=execShell(`${MRT} webui-cache-clear`); state.job=parseSemi(out); render(); setStatus("Cache cleared."); };
$("dryRun").onclick=()=>{ const kv=runLine(`${MRT} webui-marker-dry-run-line`); state.lastDryRunWouldTrigger=Number(kv.would_trigger||0); rawEl.textContent+="\n\n--- marker dry-run output ---\n"+readOutput("marker-dry-run.out").slice(0,5000); setStatus(`Marker dry-run: would trigger ${state.lastDryRunWouldTrigger}, scanned ${kv.scanned||"?"}.`); render(); };
$("bulkTrigger").onclick=()=>{ if(state.lastDryRunWouldTrigger>0&&confirm(`Trigger ${state.lastDryRunWouldTrigger} marker modules?`)) run(`${MRT} trigger-needed --yes --mode marker`); };
$("showConfig").onclick=()=>run(`${MRT} config-show`); $("autoDry").onclick=()=>{ const kv=runLine(`${MRT} webui-auto-dry-run-line`); state.lastAutoWouldTrigger=Number(kv.would_trigger||0); rawEl.textContent+="\n\n--- auto dry-run output ---\n"+readOutput("auto-dry-run.out").slice(0,5000); setStatus(`Auto dry-run: would trigger ${state.lastAutoWouldTrigger}.`); render(); }; $("autoRun").onclick=()=>{ if(state.lastAutoWouldTrigger>0&&confirm(`Run auto-trigger for ${state.lastAutoWouldTrigger} allowlisted modules?`)) run(`${MRT} auto-trigger --yes`); };
$("configOff").onclick=$("disableAuto").onclick=()=>run(`${MRT} config-auto --disable && ${MRT} config-show`); $("useSelected").onclick=()=>{ allowlistEl.value=Array.from(state.selected).join(" "); }; $("enableAllowlist").onclick=()=>{ const ids=allowlistEl.value.trim(); if(!ids){ alert("Allowlist is empty; refusing enable."); return; } if(confirm(`Enable auto config for: ${ids}? This writes config only.`)) run(`${MRT} webui-config-set-allowlist ${ids.split(/\s+/).map(shellQuote).join(" ")}`); }; $("markSelectedFresh").onclick=()=>{ for(const id of state.selected) run(`${MRT} mark-fresh ${shellQuote(id)}`); }; $("clearSelectedBaselines").onclick=()=>{ if(confirm("Clear baselines for selected modules?")) for(const id of state.selected) run(`${MRT} clear-baseline ${shellQuote(id)}`); }; $("helpBtn").onclick=()=>alert("Recommended flow:\n1. Scan online\n2. Wait for status=ok\n3. Results auto-load; or press Load latest results\n4. Review filters\n5. Use dry-run before any trigger action");
bridgeStatusEl.textContent=bridgeCandidates().length?"Shell bridge detected.":"No shell bridge detected."; try{ pollStatus(false); }catch(e){ render(); }
