const MRT = "/data/adb/modules/module-reflash-trigger/bin/mrt";
const $ = id => document.getElementById(id);
const state = { modules: [], filter: "needs", selected: new Set(), lastDryRunWouldTrigger: 0, lastAutoWouldTrigger: 0, lastMode: "online", polling: null };
const statusEl=$("status"), bridgeStatusEl=$("bridgeStatus"), rawEl=$("raw"), statsEl=$("stats"), filtersEl=$("filters"), modulesEl=$("modules"), allowlistEl=$("allowlist");
function shellQuote(s){ return "'" + String(s).replace(/'/g,"'\\''") + "'"; }
function bridgeCandidates(){ const out=[]; if(window.ksu&&typeof window.ksu.exec==="function") out.push(["ksu.exec",cmd=>window.ksu.exec(cmd)]); if(window.kernelsu&&typeof window.kernelsu.exec==="function") out.push(["kernelsu.exec",cmd=>window.kernelsu.exec(cmd)]); if(window.apatch&&typeof window.apatch.exec==="function") out.push(["apatch.exec",cmd=>window.apatch.exec(cmd)]); if(window.magisk&&typeof window.magisk.exec==="function") out.push(["magisk.exec",cmd=>window.magisk.exec(cmd)]); if(window.webui&&typeof window.webui.exec==="function") out.push(["webui.exec",cmd=>window.webui.exec(cmd)]); return out; }
function execShell(cmd){ rawEl.textContent="$ "+cmd+"\n\n"; const candidates=bridgeCandidates(); if(!candidates.length){ const msg="ERROR: no shell bridge object detected"; rawEl.textContent+=msg; throw new Error(msg); } let last=""; for(const [name,fn] of candidates){ try{ const res=fn(cmd); bridgeStatusEl.textContent="Shell bridge detected: "+name; rawEl.textContent+=String(res??""); return String(res??""); }catch(e){ last=`${name}: ${e&&e.message?e.message:e}`; } } rawEl.textContent+="ERROR: all shell bridge calls failed\n"+last; throw new Error(last); }
function parseKV(text){ const o={}; String(text||"").split(/\r?\n/).forEach(line=>{ const i=line.indexOf("="); if(i>0) o[line.slice(0,i)]=line.slice(i+1); }); return o; }
function setStatus(msg){ statusEl.textContent=msg; }
function normalize(m){ if(m.self||m.status==="self") return "blocked"; if(m.disabled||m.remove_marker||m.status==="blocked") return "blocked"; if(m.status==="local_newer_than_remote") return "local_newer"; if(m.moduleNeedsReflashMarker||(m.status==="needs_reflash"&&m.reason==="module_reported_needs_reflash_marker")) return "needs"; if(m.status==="fresh") return "fresh"; if(m.needs_reflash||m.status==="needs_reflash"||m.reason==="remote_fingerprint_changed_since_last_fresh") return "drift"; return "unknown"; }
function counts(){ const c={needs:0,fresh:0,drift:0,unknown:0,local_newer:0,blocked:0,total:state.modules.length}; state.modules.forEach(m=>c[normalize(m)]++); return c; }
function renderStats(){ const c=counts(); const items=[["needs","Needs reflash",c.needs,"Manager marker"],["fresh","Fresh",c.fresh,"Baseline matches"],["drift","Drift",c.drift,"Diagnostic only"],["unknown","Unknown",c.unknown,"No baseline yet"],["local_newer","Local newer",c.local_newer,"No trigger"],["blocked","Blocked",c.blocked,"Unsafe target"],["all","Total",c.total,"updateJson-capable"]]; statsEl.innerHTML=items.map(([key,label,val,sub])=>`<button class="mrt-stat ${state.filter===key?"active":""}" data-filter="${key}"><span>${label}</span><strong>${val}</strong><small>${sub}</small></button>`).join(""); statsEl.querySelectorAll("button[data-filter]").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter; render();}); }
function renderFilters(){ const f=[["needs","Needs reflash"],["fresh","Fresh"],["drift","Drift"],["unknown","Unknown"],["local_newer","Local newer"],["blocked","Blocked"],["all","All"]]; filtersEl.innerHTML=f.map(([k,l])=>`<button class="chip ${state.filter===k?"active":""}" data-filter="${k}">${l}</button>`).join(""); filtersEl.querySelectorAll("button[data-filter]").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter; render();}); }
function field(label,value){ if(value===undefined||value===null||value==="") return ""; return `<div class="field"><span>${label}</span><code>${String(value)}</code></div>`; }
function card(m){ const n=normalize(m), checked=state.selected.has(m.id)?"checked":""; return `<article class="mrt-card ${n}"><div class="card-head"><div><label><input type="checkbox" data-select="${m.id}" ${checked}> <strong>${m.name||m.id}</strong></label><p><code>${m.id}</code></p></div><span class="badge ${n}">${n}</span></div><div class="fields">${field("version",m.version)}${field("versionCode",m.versionCode)}${field("remote",m.remoteVersion)}${field("remoteCode",m.remoteCode)}${field("reason",m.reason)}${field("marker",m.moduleNeedsReflashMarker)}${field("triggerable",m.triggerable)}</div><div class="card-actions"><button data-act="status" data-id="${m.id}">Status online</button><button class="danger" data-act="trigger" data-id="${m.id}" ${m.triggerable?"":"disabled"}>Trigger this module</button><button data-act="fresh" data-id="${m.id}">Mark fresh</button><button data-act="freshCached" data-id="${m.id}">Mark fresh cached</button><button data-act="baseline" data-id="${m.id}">Baseline</button><button data-act="clear" data-id="${m.id}">Clear baseline</button><button data-act="restore" data-id="${m.id}">Restore latest</button></div></article>`; }
function renderModules(){ let list=state.modules; if(state.filter!=="all") list=list.filter(m=>normalize(m)===state.filter); modulesEl.innerHTML=list.length?list.map(card).join(""):`<div class="empty">No modules in this filter.</div>`; modulesEl.querySelectorAll("input[data-select]").forEach(cb=>cb.onchange=()=>{ if(cb.checked) state.selected.add(cb.dataset.select); else state.selected.delete(cb.dataset.select); }); modulesEl.querySelectorAll("button[data-act]").forEach(b=>b.onclick=()=>moduleAction(b.dataset.act,b.dataset.id)); }
function render(){ renderStats(); renderFilters(); renderModules(); $("bulkTrigger").disabled=state.lastDryRunWouldTrigger<=0; $("autoRun").disabled=state.lastAutoWouldTrigger<=0; }
function startScan(mode){ state.lastMode=mode; setStatus(`Starting ${mode} scan…`); state.modules=[]; render(); execShell(`${MRT} webui-scan-start ${mode}`); if(state.polling) clearInterval(state.polling); state.polling=setInterval(()=>pollStatus(true),2000); pollStatus(true); }
function pollStatus(loadWhenOk=false){ const kv=parseKV(execShell(`${MRT} webui-status`)); setStatus(`job=${kv.status||"?"} mode=${kv.mode||"?"} ${kv.message||""}`); if(loadWhenOk&&kv.status==="ok"){ clearInterval(state.polling); state.polling=null; loadScan(kv.mode||state.lastMode); } if(kv.status==="failed"){ clearInterval(state.polling); state.polling=null; } }
function readChunks(mode){ let offset=0, chunks=[], limit=4096; for(let i=0;i<80;i++){ const part=execShell(`${MRT} webui-read ${mode} ${offset} ${limit}`); chunks.push(part); offset+=part.length; if(part.length<limit) break; } return chunks.join(""); }
function loadScan(mode){ setStatus(`Loading ${mode} scan…`); const text=readChunks(mode); rawEl.textContent=`Loaded ${text.length} chars from ${mode} scan cache\n\n`+text.slice(0,4000); try{ state.modules=JSON.parse(text); setStatus(`Loaded ${state.modules.length} modules from ${mode} cache.`); }catch(e){ setStatus(`JSON parse failed: ${e.message}`); } render(); }
function run(cmd){ try{ const out=execShell(cmd); setStatus("Command finished."); return out; }catch(e){ setStatus("Command failed: "+e.message); return ""; } }
function moduleAction(act,id){ const q=shellQuote(id); if(act==="trigger"&&!confirm(`Trigger ${id}? This lowers version/versionCode only. Your manager must perform the actual reflash.`)) return; const map={status:`${MRT} status-online ${q}`,trigger:`${MRT} trigger --yes ${q}`,fresh:`${MRT} mark-fresh ${q}`,freshCached:`${MRT} mark-fresh-cached ${q}`,baseline:`${MRT} baseline-show --online ${q}`,clear:`${MRT} clear-baseline ${q}`,restore:`${MRT} restore-latest ${q}`}; run(map[act]||`${MRT} status-online ${q}`); }
$("scanOnline").onclick=()=>startScan("online"); $("scanLocal").onclick=()=>startScan("local"); $("refreshJob").onclick=()=>pollStatus(false); $("dryRun").onclick=()=>{ const out=run(`${MRT} trigger-needed --dry-run --mode marker`); const m=out.match(/trigger_needed_dry_run_would_trigger=(\d+)/); state.lastDryRunWouldTrigger=m?Number(m[1]):0; render(); }; $("bulkTrigger").onclick=()=>{ if(state.lastDryRunWouldTrigger>0&&confirm(`Trigger ${state.lastDryRunWouldTrigger} marker modules?`)) run(`${MRT} trigger-needed --yes --mode marker`); }; $("showConfig").onclick=()=>run(`${MRT} config-show`); $("autoDry").onclick=()=>{ const out=run(`${MRT} auto-trigger --dry-run`); const m=out.match(/auto_trigger_dry_run_would_trigger=(\d+)/); state.lastAutoWouldTrigger=m?Number(m[1]):0; render(); }; $("autoRun").onclick=()=>{ if(state.lastAutoWouldTrigger>0&&confirm(`Run auto-trigger for ${state.lastAutoWouldTrigger} allowlisted modules?`)) run(`${MRT} auto-trigger --yes`); }; $("configOff").onclick=$("disableAuto").onclick=()=>run(`${MRT} config-auto --disable && ${MRT} config-show`); $("useSelected").onclick=()=>{ allowlistEl.value=Array.from(state.selected).join(" "); }; $("enableAllowlist").onclick=()=>{ const ids=allowlistEl.value.trim(); if(!ids){ alert("Allowlist is empty; refusing enable."); return; } if(confirm(`Enable auto config for: ${ids}? This writes config only.`)) run(`${MRT} webui-config-set-allowlist ${ids.split(/\s+/).map(shellQuote).join(" ")}`); }; $("markSelectedFresh").onclick=()=>{ for(const id of state.selected) run(`${MRT} mark-fresh ${shellQuote(id)}`); }; $("clearSelectedBaselines").onclick=()=>{ if(confirm("Clear baselines for selected modules?")) for(const id of state.selected) run(`${MRT} clear-baseline ${shellQuote(id)}`); };
bridgeStatusEl.textContent=bridgeCandidates().length?"Shell bridge detected.":"No shell bridge detected."; render();
